### ISSUE TITLE
tensorflow error

### ISSUE THREAD

**Issue by SJKbiophy6** [YoshitakaMo/localcolabfold#2]
As issued WJluluxiu on the other issue page, there is a tensorflow error and I got the following error messages.
![image](https://user-images.githubusercontent.com/38548498/133050694-fe2d0ac9-ae76-4870-af28-cd397b46d968.png)

My server has 4 x 1080Ti GPUs on CentOS7.

**Comment by YoshitakaMo** [comment]
What is your CUDA version? Is it 11.1.105 or more?

**Comment by SJKbiophy6** [comment]
Thank you. the Cuda version is 9.2, I think.

`nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Tue_Jun_12_23:07:04_CDT_2018
Cuda compilation tools, release 9.2, V9.2.148
`

**Comment by YoshitakaMo** [comment]
Because `install_colabfold_linux.sh` installs tensorflow-gpu 2.5.0 which depends on CUDA 11, your environment may not be sufficient to run `localcolabfold`. See https://www.tensorflow.org/install/source?hl=en#gpu .
Please upgrade your cuda driver to 11.1, 11.2 or more and try the installation again.

**Comment by ulupo** [comment]
I too experienced errors which ended up being due to not having version 11.1 or higher of the CUDA drivers.  In my case, the relevant portion of the traceback looked like:
```
2021-09-15 22:06:36.025661: W external/org_tensorflow/tensorflow/stream_executor/gpu/asm_compiler.cc:81] Couldn't get ptxas version string: Internal: Couldn't invoke ptxas --version
2021-09-15 22:06:36.026239: F external/org_tensorflow/tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:479] ptxas returned an error during compilation of ptx to sass: 'Internal: Failed to launch ptxas'  If the error message indicates that a file could not be written, please verify that sufficient filesystem space is provided.
```

However, typing `nvidia-smi` on the Ubuntu terminal yielded
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.63.01    Driver Version: 470.63.01    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
|  0%   35C    P8     9W / 350W |     98MiB / 24245MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1219      G   /usr/lib/xorg/Xorg                 85MiB |
|    0   N/A  N/A      1425      G   /usr/bin/gnome-shell               10MiB |
+-----------------------------------------------------------------------------+
```
which rather made it looked like I did have CUFA Version 11.4.  Then I noticed that typing `nvcc --version` gave
```
(/home/lupo/Workspace/colabfold/colabfold-conda) lupo@SV-91L-002:~/Workspace/colabfold$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
```
Which left me rather confused as an inexperienced GPU user.  Why does one command show a version 11.4 and the other a version 10.1?  I ran both `sudo apt install nvidia-cuda-toolkit` (which I now think was a mistake) and updated the CUDA drivers according to the instructions in https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=20.04&target_type=deb_local.  But `nvcc --version` still showed version 10.1, and i still got the compilation error when launching `runner.py`.

The solution came from stumbling upon https://stackoverflow.com/a/53504578 where it is explained that what I had been looking at were two different things under the CUDA umbrella.  It turned out there are some "Mandatory post-installation actions" listed in https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#post-installation-actions which I had not performed after updating CUDA.  After performing them, `nvcc --version` also shows version 11.4 and I am able to run my first localcolabfold experiment!

I hope this story can be of help.

**Comment by YoshitakaMo** [comment]
Yes, the return values `nvidia-smi` and `nvcc --version` are different. We have to make sure the value of `nvcc --version`, not `nvidia-smi`.

**Comment by ulupo** [comment]
Thanks for the reply @YoshitakaMo!

> Yes, the return values nvidia-smi and nvcc --version are different. We have to make sure the value of nvcc --version, not nvidia-smi.

Indeed.  Do you think it would be good to add this detail to the README?

**Comment by YoshitakaMo** [comment]
> Do you think it would be good to add this detail to the README?
Yes, I've added it. I appreciate your examination and kind proposal!
