### ISSUE TITLE
Question: If it possible to run MSA locally with the native alphafold database?

### ISSUE THREAD

**Issue by Willwyy** [YoshitakaMo/localcolabfold#203]
Hi,

Thank you very much to share this amazing and user-friendly code, and give us access to the default MSA server. Here, I have a stupid question: is it possible to also run the MSA step loaclly? Of course it should be ran with the local huge alphafold database. If it is possible, could you please give me some hint to set it? I am not very good at these computer things, sorry to bother you if the question is annoying.

Thank you very much again for sharing the code! It really helped me a lot!

**Comment by YoshitakaMo** [comment]
MSA generation on a local computer is now supported. First, Use https://github.com/sokrypton/ColabFold/blob/main/setup_databases.sh to set up the sequence database for ColabFold. Note that MMseqs2 (its commit hash `71dd32ec43e3ac4dabf111bbc4b124f1c66a85f1` is recommended) is required for it.
My installation log of the database, test run example of `colabfold_search` to generate MSA, and `colabfold_batch` to predict the structure with the generated one are shown at https://qiita.com/Ag_smith/items/bfcf94e701f1e6a2aa90 (written in Japanese, sorry).

Note that you need at least **768GB of RAM** to make MSA at the same speed as the ColabFold Notebook from a web browser. Otherwise, it will take about 20-30 minutes to generate MSA.

**Comment by Willwyy** [comment]
Thank you very much for your reply! It really helps us a lot, thank you!
