### ISSUE TITLE
AMD GPU compatibility

### ISSUE THREAD

**Issue by Lucmeister55** [YoshitakaMo/localcolabfold#41]
Perhaps a redundant question but I'm asking it anyway as I lack the expertise to verify it entirely on my own, but is it theoretically possible (and if so, how) to run colabfold locally with an AMD GPU (specifically a radeon rx 580) through another API such as Vulkan or openCL instead of Cuda?

**Comment by YoshitakaMo** [comment]
Because ColabFold/AlphaFold is written in JAX and Tensorflow, I think it's theoretically possible to accelerate the prediction if the two support AMD GPUs. However, to the best of my knowledge, it's not currently supported.
In the discussion of https://github.com/google/jax/issues/2012, the developers successfully trained using JAX with AMD W6800 graphics board. However, we must compile JAX from source to do it, which is very painful. and I don't know whether the compilation also work on macOS as well as Linux.

**Comment by Lucmeister55** [comment]
Thank you!
